### ISSUE TITLE
As a user I want to send a message using a contact form

### ISSUE THREAD

**Issue by adam-fu** [simple-swiss-code/wallpaper_2020#4]
We like to have a contact form in the website. There is a [list of static contact forms](https://jekyllthemes.io/resources/jekyll-contact-forms) we can go with formspree but we should also have a brief look and discuss the others.
[getform]( Is a nice alternative and also supports [captcha](https://getform.io/docs/collecting-submissions/spam-filtering-with-recaptcha) and it has free file upload.
We will go with **getform**

Mandatory fields:
* Name
* Message
* Email or phone
Optional fields
* How did you find us? (select options)
* file upload

Estimate: 5h

**Comment by nthungvn** [comment]
Hey Adam,
I think we can consider again if we can continue use getform. They said they only free 100 submissions once for every free account, will be not reset every month.
![image](https://user-images.githubusercontent.com/9164553/82727266-a49e5200-9d13-11ea-912f-e33af0f93e1f.png)

**Comment by adam-fu** [comment]
wow, i overread that :(

**Comment by adam-fu** [comment]
How about https://formik.com ?
